name: Update Website
on:
  push:
    branch:
      - master

jobs:
  build:
    name: Deploy Vuepress
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build Site
      run: npm run build
    - name: Set CNAME
      run: |-
        cd src/.vuepress/dist
        echo discord-bot.syntony666.com > CNAME
    - name: Commit the Page
      run: |-
        cd src/.vuepress/dist
        git init
        git remote add origin https://@github.com/syntony666/discord-bot-doc.git
        git add -A
        git config --global user.name "syntony666"
        git config --global user.email syntony666@github.com
        git commit -m 'deploy'
    - name: Depoly to GitHub Page
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'gh-pages'
        force: true
        directory: 'src/.vuepress/dist'
