name: Update Website
on:
  push:
    branch:
      - master

jobs:
  build:
    name: Install vue-page
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build Site
      run: npm run build
    - name: Set CNAME
      run: cd src/.vuepress/dist
      run: echo discord-bot.syntony666.com > CNAME
    - name: Depoly to GitHub Page
      run: |-
        call git init
        call git add -A
        call git commit -m 'deploy'
        call git push -f https://github.com/syntony666/discord-bot-doc.git master:gh-pages
