name: Update Website
on:
  push:
    branch:
      - master

jobs:
  build:
    name: Install vue-page
    runs-on: ubuntu-latest
    uses: actions/setup-node@v1
    steps:
    - name: Install dependencies
      run: npm ci
    - name: Build Site
      run: npm run build
    - name: Set CNAME
      run: echo discord-bot.syntony666.com > CNAME
    - name: Depoly to GitHub Page
      run: |-
        call git init
        call git add -A
        call git commit -m 'deploy'
        call git push -f https://github.com/syntony666/discord-bot-doc.git master:gh-pages

